channels:
  - pytorch
  - nvidia
  - conda-forge
  - pyviz
dependencies:
  - pip
  - pytorch=1.13
  - pytorch-cuda=11.6
  - pyinterp
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - xrft
  - scipy
  - matplotlib
  - holoviews
  - pip:
    - pytorch-lightning==1.8.*
    - hydra-core