# @package _global_

paths:
    sound: /DATASET/eNATL/eNATL60_BLB002_sound_speed_0_1000m_regrid.nc
    variables: /DATASET/eNATL/eNATL60_BLB002_cutoff_freq_0_1000m_regrid.nc


trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  min_epochs: 0
  max_epochs: 300
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_loss
      save_top_k: 1
      filename: '{val_loss:.2f}-{epoch:02d}'
      mode: min

datamodule:
  _target_: src.data.AcousticPredictorDatamodule
  input_da: 
    _target_: src.utils.load_acoustic_variables
    path1: ${paths.sound}
    path2: ${paths.variables}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: [0, 254]}
    val: 
      time: {_target_: builtins.slice, _args_: [254, 331]}
    test: 
      time: {_target_: builtins.slice,  _args_: [331, 365]}
  dl_kw: {batch_size: 4, num_workers: 16}

model:
  _target_: src.acoustic_predictor.AcousticPredictor
  input_depth: 107
  lr: 0.001
  acoustic_variables: 2


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}

