# @package _global_

paths:
  celerity:
    train: /DATASET/eNATL/eNATL60_BLB002_sound_speed_regrid_0_1000m.nc
    #test: /DATASET/NATL/NATL60-CJM165-ssh-2012-2013-${resolution}.nc
    test: /DATASET/NATL/NATL60GULF-CJM165_sound_speed_regrid_0_1000m.nc
  accoustic:
    train: /DATASET/envs/o23gauvr/tmp/eNATL60_BLB002_ECS_at_0_regrid_0_1000m.nc
    test: /DATASET/envs/o23gauvr/tmp/NATL60GULF-CJM165_ECS_at_0_regrid_0_1000m.nc
    
spatial_domain:
  lon: {_target_: builtins.slice, _args_: [-64,-55]}
  lat: {_target_: builtins.slice, _args_: [31,43]}

#accoustic_training: False


trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  logger: 
    #_target_: pytorch_lightning.loggers.CSVLogger
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: /homes/o23gauvr/Documents/thèse/code/FASCINATION/outputs/enatl_natl/accoustic_predictor
    name: ${now:%Y-%m-%d_%H-%M}
    #version: ${now:%Y-%m-%d_%H-%M}
  min_epochs: 0
  max_epochs: 1000
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 1
      filename: '{val_mse:.2f}-{epoch:02d}'
      mode: min



dm:
  accoustic_var: ecs
  ###! for now we restrict acc_var to one variable
      #- ecs
      #- cutoff_freq
    
  xrds_kw:
    patch_dims: {time: 1} #{time: 15, lat: 220, lon: 180}  ###! necessary if use of conv2D
    strides: {time: 1} #{time: 1, lat: 220, lon: 180}
    check_full_scan: True
    check_dim_order: True
    # rec_weight:
    #   crop: {time: 0, lat: 20, lon: 20}
    #   offset: 1
  
  #aug_kw: {aug_factor: 2, aug_only: true}
  dl_kw: {batch_size: 4, num_workers: 1}

train_dm:
  _target_: dev.data_enatl_natl.Enatl_Natl_DataModule
  loaded_da:
    _target_: dev.data_enatl_natl.load_data
    celerity_path: ${paths.celerity.train}
    accoustic_path: ${paths.accoustic.train}
    acc_var: ${dm.accoustic_var}
    spatial_domain: ${spatial_domain}
  time_domain: 
    train:
      time: {_target_: builtins.slice, _args_: ['2009-08-12', '2010-06-30']}

    val:
      time: {_target_: builtins.slice, _args_: ['2009-07-01', '2009-08-11']}

    test: null

  xrds_kw: ${dm.xrds_kw}
    #domain_limits: null 
  dl_kw: ${dm.dl_kw}
  norm_stats:
    mean: 1513.9706701708644
    std: 15.007288853760143
    #domain_limits: ${domains.train}



test_dm:
  _target_: dev.data_enatl_natl.Enatl_Natl_DataModule
  loaded_da:
    _target_: dev.data_enatl_natl.load_data
    _partial_: False
    celerity_path: ${paths.celerity.test}
    accoustic_path: ${paths.accoustic.test}
    acc_var: ${dm.accoustic_var}
    spatial_domain: ${spatial_domain}
  time_domain: 
    train: null
    val: null
    test: 
      time: {_target_: builtins.slice, _args_: ['2012-10-01', '2013-09-30']}

  xrds_kw: 
    patch_dims: ${dm.xrds_kw.patch_dims}
    strides: ${dm.xrds_kw.strides}
    check_full_scan: ${dm.xrds_kw.check_full_scan}
    check_dim_order: ${dm.xrds_kw.check_dim_order}
    #domain_limits: null 
  dl_kw: ${dm.dl_kw}
  norm_stats:
    mean: 1511.844605664954
    std: 15.242737332216553



model:
  _target_: dev.acoustic_predictor.AcousticPredictor
  input_depth: 107
  acoustic_variables: 
    _target_: builtins.len
    s: ${dm.accoustic_var}

  opt_fn:
    _target_: dev.AutoEncoder_v2.AutoEncoder.cosanneal_lr_adamw
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
    weight_decay: 1e-2


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: dev.train.base_training  # fit + test
    trainer: ${trainer}
    lit_mod: ${model}
    train_dm: ${train_dm}
    test_dm: ${test_dm}


defaults:
  #domain: gf_15x15
  - _self_
