# @package _global_

paths:
    sound: /DATASET/eNATL/eNATL60_BLB002_sound_speed_0_1000m_regrid.nc

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 2
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  min_epochs: 0
  max_epochs: 200
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_loss
      save_top_k: 1
      filename: '{val_loss:.2f}-{epoch:02d}'
      mode: min

datamodule:
  _target_: src.data.AutoEncoderDatamodule
  input_da: 
    _target_: src.utils.load_sound_speed_fields
    path: ${paths.sound}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2009-10-20', '2010-06-30']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2009-08-06', '2009-10-19']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2009-07-01', '2009-08-05']}
  dl_kw: {batch_size: 4, num_workers: 32}

model:
  _target_: src.autoencoder.Autoencoder
  lr: 0.001


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}

