# @package _global_

paths:
    ssh: data/NATL60-CJM165_NATL_ssh_y2013.1y.nc
    sst: data/NATL60-CJM165_NATL_sst_y2013.1y.nc

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
#  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 300
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: src.early_stopping.ValidEarlyStopping
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_loss
      save_top_k: 5
      filename: '{val_loss:.2f}-{epoch:02d}'
      mode: min

datamodule:
  _target_: src.data.BaseDataModule
  input_da: 
    _target_: src.utils.load_data
    path: ${ssh}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2013-02-24', '2013-09-30']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2012-12-15', '2013-02-24']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2012-10-01', '2012-12-20']}
  xrds_kw:
    patch_dims: { time: 15, lat: 240, lon: 240}
    strides: { time: 1, lat: 240, lon: 240}
  dl_kw: {batch_size: 4, num_workers: 1}
  aug_factor: 0
  aug_only: False

model:
  _target_: src.models.Lit4dVarNet
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: 175
  rec_weight:
      _target_: src.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 20, lon: 20}
  solver: 
    _target_: src.models.GradSolver
    n_step: 10
    lr_grad: 0.2
    prior_cost: 
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 32
      downsamp: 2
    obs_cost: 
      _target_: src.models.BaseObsCost
    grad_mod: 
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 48


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    test_fn: null
      # _target_: src.utils.diagnostics
      # _partial_: true
      # test_domain:
      #   time: {_target_: builtins.slice, _args_: ["2012-10-22", "2012-12-02"]}
      #   lat: {_target_: builtins.slice, _args_: [33, 43]}
      #   lon: {_target_: builtins.slice, _args_: [-65, -55]}
