# @package _global_

paths:
    sound: /Odyssey/public/enatl60/celerity/eNATL60_BLB002_sound_speed_regrid_0_botm.nc #/Odyssey/public/enatl60/celerity/eNATL60_BLB002_sound_speed_regrid_0_1000m.nc #/Odyssey/public/enatl60/celerity/eNATL60_BLB002_sound_speed_regrid_0_botm.nc
    #variables: /DATASET/envs/o23gauvr/tmp/eNATL60_BLB002_ECS_at_0_regrid_0_1000m.nc


normalization:
  min_max:
    x_min: null #1459.0439165829073
    x_max: null #1545.8698054910844
  mean_std:
    mean: null #1513.8417292146794 
    std: null #14.949060449731395 
  mean_std_along_depth:
    mean: null 
    std: null 



dtype: float64 #float16 #float64 

root_save_dir: /Odyssey/private/o23gauvr/code/FASCINATION/outputs #/DATASET/envs/o23gauvr/outputs #/homes/o23gauvr/Documents/thèse/code/FASCINATION/outputs

save_dir_name: test #channels_${model.model_hparams.channels_list}

model_architecture: AE_Dense

patience: 5

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  logger: 
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: ${root_save_dir}/${save_dir_name}/AE/  #/DATASET/envs/o23gauvr/outputs/AE_V2/ #/homes/o23gauvr/Documents/thèse/code/FASCINATION/outputs/AE_V2/
    name: ${model.model_name}    #ecs_${model.loss_weight.ecs_weight}
    version: pred_${model.loss_weight.prediction_weight}_weighted_${model.loss_weight.weighted_weight}_gradient_${model.loss_weight.gradient_weight}_error_treshold_${model.loss_weight.error_treshold_weight}_max_pos_${model.loss_weight.max_position_weight}_max_value_${model.loss_weight.max_value_weight}_min_max_pos_${model.loss_weight.min_max_position_weight}_min_max_value_${model.loss_weight.min_max_value_weight}_fft_${model.loss_weight.fft_weight}_ecs_${model.loss_weight.ecs_weight}/lr_${model.opt_fn.lr}/normalization_${datamodule.norm_stats.method}/manage_nan_${datamodule.manage_nan}/${model_config.save_dir.${model_architecture}}/${now:%Y-%m-%d_%H-%M}
    log_graph : True

  max_epochs: 1

  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_loss
      save_top_k: 1
      filename: '{val_loss:.2f}-{epoch:02d}'
      mode: min
    - _target_: pytorch_lightning.callbacks.EarlyStopping
      monitor: val_loss
      verbose: True
      patience: ${trainer.max_epochs}
      min_delta: 1e-6
      #patience: ${patience}
    

      

datamodule:
  _target_: src.autoencoder_datamodule_1D.AutoEncoderDatamodule_1D
  input_da: 
    _target_: src.utils.load_ssp_da
    ssf_da_path: ${paths.sound}
  dl_kw:
    batch_size: 16
    num_workers: 2
  norm_stats:
    method:  mean_std_along_depth #min_max #min_max #mean_std_along_depth #mean_std #mean_std_along_depth #mean_std  #min_max
    params: ${normalization.${datamodule.norm_stats.method}}
    norm_location: AE #datamodule #AE
  manage_nan: supress_with_max_depth
  profile_ratio: -1 
  data_selection: spatial_sampling #spatial_sampling
  

  
  #pooled_dim: ${pooled_dim} #spatial #depth  #all
    
    #${model_config.depth_pre_treatment.${model_config.model_hparams.${model.model_name}.pooling_dim}.${datamodule.depth_pre_treatment.method}}

  dtype_str: ${dtype}  



model:
  _target_: src.autoencoder_V2.AutoEncoder
  model_name: ${model_architecture} #_3D
  model_hparams: ${model_config.model_hparams.${model.model_name}}
  specific_last_act_fn: null #auto #null #Identity #Sigmoid #Tanh #Identity #LeakyRelu
  opt_fn:
    _target_: src.utils.cosanneal_lr_adamw
    _partial_: true
    lr: 1e-3
    T_max: 100000 #${trainer.max_epochs} #${trainer.max_epochs} #${trainer.max_epochs} #100000
    weight_decay: 1e-3 #0 #1e-3
  loss_weight:
    prediction_weight: 1 #10 #0.5 #0.01 #1
    weighted_weight: 1 #100 
    gradient_weight: 0 #1000000
    error_treshold_weight: 0
    max_position_weight: 0 #0.01 
    max_value_weight: 0 #100 
    min_max_position_weight: 0 #0.01 
    min_max_value_weight: 0 #100 
    fft_weight: 0 #0.01
    ecs_weight: 0
  


model_config:


  model_hparams:

    AE_Dense:
      features_list: [5000,3000,1000,10]
      act_fn_str: LeakyRelu
      dropout_proba: 0.
      #dtype_str: ${dtype}


  save_dir:
    AE_Dense: features_${model.model_hparams.features_list}  #_linear_layer_${model.model_hparams.linear_layer}_dropout_${model.model_hparams.dropout_proba}/


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}



hydra:
  run:
    dir: ${trainer.logger.save_dir}/${trainer.logger.name}/${trainer.logger.version} #/Odyssey/private/o23gauvr/code/FASCINATION 

  job:
    env_set: 
      CUDA_VISIBLE_DEVICES: 0
      
      #TORCH_USE_CUDA_DSA: 1

# torch:
#   backends:n
#     cudnn:
#       allow_tf32: False
